#!/bin/sh

# 1. 변경된 파일 목록 가져오기
stagedFiles=$(git diff --staged --name-only)

# 2. 변경된 파일들에 대하여 Spotless를 실행해 코드 컨벤션을 적용
if [ -n "$stagedFiles" ]; then
    echo "Running spotlessApply on staged files: $stagedFiles"
    ./gradlew spotlessApply --daemon -PspotlessFiles="$stagedFiles"
else
    echo "No files to format."
    exit 0
fi

# 3. Spotless를 통해 변경된 파일들을 다시 추가
for file in $stagedFiles; do
    if test -f "$file"; then
        git add "$file"
    fi
done
